
export default () => ({
   // this variable is for selected movie
   selectedMovie:null,
   // this is the main json
   cinema: [{
         id: 1,
         movie: "children of heaven",
         releasDate: "2018/4/20",
         year: "1997",
         dsc: `Ali's family lives in a poor South Tehran neighbourhood, and are having financial trouble, so he fears to tell his parents about the mishap. The landlord argues with Ali's mother because she is five months behind on the rent, and the grocer has not been paid in a while either. Ali tells Zahra about the shoes and begs her not to tell their mother; she agrees. That night, Ali's father scolds him for not helping his ill mother when she asked. While the siblings were doing their homework, they passed notes to each other discussing what to do. `,
         releasTime: "22:00",
         directedBy: "	Majid Majidi",
         starring: [
            "Mohammad Amir Naji",
            " Amir Farrokh Hashemian",
            "Bahare Seddiqi"
         ],
         img: "/movies/Children_of_heaven.jpg",
         seats: [
            {available:false,user:false,id:1,selected:false},
            {available:true,user:false,id:2,selected:false},
            {available:true,user:false,id:3,selected:false},
            {available:true,user:false,id:4,selected:false},
            {available:true,user:false,id:5,selected:false},
            {available:true,user:false,id:6,selected:false},
            {available:false,user:false,id:7,selected:false},
            {available:true,user:false,id:8,selected:false},
            {available:true,user:false,id:9,selected:false},
            {available:false,user:false,id:10,selected:false},
            {available:true,user:false,id:11,selected:false},
            {available:true,user:false,id:12,selected:false},
            {available:false,user:false,id:13,selected:false},
            {available:true,user:false,id:14,selected:false},
            {available:true,user:false,id:15,selected:false},
            {available:true,user:false,id:16,selected:false},
            {available:true,user:false,id:17,selected:false},
            {available:true,user:false,id:18,selected:false},
            {available:true,user:false,id:19,selected:false},
            {available:true,user:false,id:20,selected:false}]
         

      },
      {
         id: 2,
         movie: "about elly",
         releasDate: "2018/4/20",
         year: "2009",
         starring: ["	Golshifteh Farahani",
            "Taraneh Alidoosti",
            "Shahab Hosseini",
            "Mani Haghighi",
            "Merila Zarei",
            "Peyman Moaadi",
            "Ahmad Mehranfar",
            "Rana Azadivar",
            "Saber Abar"
         ],
         directedBy: "Asghar Farhadi",
         dsc: " group of middle-class Iranians, former classmates at the law faculty of the university, go to the Caspian Sea for a three-day vacation: Sepideh, her husband Amir and their young daughter; Shohreh, her husband Peymān and their two children, including their son Arash and Nāzy and her husband Manuchehr. Sepideh, who planned the trip, brings along her daughter's kindergarten teacher, Elly, in order to introduce her to Ahmad, a divorced friend visiting from Germany.",
         releasTime: "20:00",
         img: "/movies/About_elly.jpg",
         seats:[
            {available:false,user:false,id:1,selected:false},
            {available:true,user:false,id:2,selected:false},
            {available:true,user:false,id:3,selected:false},
            {available:false,user:false,id:4,selected:false},
            {available:true,user:false,id:5,selected:false},
            {available:true,user:false,id:6,selected:false},
            {available:false,user:false,id:7,selected:false},
            {available:true,user:false,id:8,selected:false},
            {available:true,user:false,id:9,selected:false},
            {available:false,user:false,id:10,selected:false},
            {available:true,user:false,id:11,selected:false},
            {available:true,user:false,id:12,selected:false},
            {available:false,user:false,id:13,selected:false},
            {available:true,user:false,id:14,selected:false},
            {available:false,user:false,id:15,selected:false},
            {available:true,user:false,id:16,selected:false},
            {available:true,user:false,id:17,selected:false},
            {available:false,user:false,id:18,selected:false},
            {available:true,user:false,id:19,selected:false},
            {available:true,user:false,id:20,selected:false}]

      },
      {
         id: 3,
         movie: "A separation",
         releasDate: "2018/4/22",
         directedBy: "Asghar Farhadi",
         starring: ["Leila Hatami",
            "Peyman Moaadi",
            "Shahab Hosseini",
            "Kimiya Hosseini",
            "Babak Karimi",
            " Sareh Bayat",
            "Sarina Farhadi",
            "Merila Zarei"
         ],
         year: "2011",
         dsc: "Simin desperately wants to leave Iran with Nader, her husband of 14 years, and their daughter, Termeh. Nader, however, is concerned for his elderly father, who suffers from Alzheimer's disease. Simin files for divorce, but the family court judges the couple's problems insufficient to warrant divorce and rejects Simin's application.",
         releasTime: "18:00",
         img: "/movies/A_Separation.png",
         seats:[
            {available:false,user:false,id:1,selected:false},
            {available:false,user:false,id:2,selected:false},
            {available:true,user:false,id:3,selected:false},
            {available:false,user:false,id:4,selected:false},
            {available:true,user:false,id:5,selected:false},
            {available:true,user:false,id:6,selected:false},
            {available:false,user:false,id:7,selected:false},
            {available:true,user:false,id:8,selected:false},
            {available:false,user:false,id:9,selected:false},
            {available:false,user:false,id:10,selected:false},
            {available:true,user:false,id:11,selected:false},
            {available:true,user:false,id:12,selected:false},
            {available:false,user:false,id:13,selected:false},
            {available:true,user:false,id:14,selected:false},
            {available:false,user:false,id:15,selected:false},
            {available:true,user:false,id:16,selected:false},
            {available:true,user:false,id:17,selected:false},
            {available:false,user:false,id:18,selected:false},
            {available:true,user:false,id:19,selected:false},
            {available:true,user:false,id:20,selected:false}]

      },
      {
         id: 4,
         movie: "the salesman",
         releasDate: "2018/4/21",
         year: "2016",
         directedBy: "Asghar Farhadi",
         starring: ["Shahab Hosseini",
            "Taraneh Alidoosti"
         ],
         dsc: "Emad and Rana are a married couple who both work in the theatre, currently starring in a production of Death of a Salesman by Arthur Miller, with Emad portraying Willy Loman and Rana playing Linda. Emad is also a popular instructor at a local school, where the youth joke about him being a salesman. One night, their apartment begins to collapse and they flee the building with the other residents. ",
         releasTime: "18:00",
         img: "/movies/The_Salesman.png",
         seats: [
            {available:false,user:false,id:1,selected:false},
            {available:true,user:false,id:2,selected:false},
            {available:true,user:false,id:3,selected:false},
            {available:false,user:false,id:4,selected:false},
            {available:true,user:false,id:5,selected:false},
            {available:true,user:false,id:6,selected:false},
            {available:false,user:false,id:7,selected:false},
            {available:true,user:false,id:8,selected:false},
            {available:true,user:false,id:9,selected:false},
            {available:false,user:false,id:10,selected:false},
            {available:true,user:false,id:11,selected:false},
            {available:true,user:false,id:12,selected:false},
            {available:false,user:false,id:13,selected:false},
            {available:true,user:false,id:14,selected:false},
            {available:false,user:false,id:15,selected:false},
            {available:false,user:false,id:16,selected:false},
            {available:true,user:false,id:17,selected:false},
            {available:false,user:false,id:18,selected:false},
            {available:false,user:false,id:19,selected:false},
            {available:true,user:false,id:20,selected:false}]

      },
      {
         id: 5,
         movie: "the elephant king",
         releasDate: "2018/4/21",
         year: "2017",
         releasTime: "20:00",
         directedBy: "Hadi Muhammadian",
         starring: [
            "Saeed Sheikhzade",
            "Bahram Zand",
            "Naser Tahmasb",
            "Mirtaher Mazloomi",
            "Shokat Hojjat",
            "Zohre Shokoofande",
            "Hamed Azizi",
            "George Petrosi",
            "Bahman Hashemi",
            "Akbar Manafi",
            "Shayan Shambiati"
         ],
         dsc: "The story revolves around the society of elephants in a jungle in Africa. Shadphil (the elephant king’s son) is supposed to rule the society after his father.",
         img: "/movies/The_Elephant_King.jpg",
         seats: [
            {available:false,user:false,id:1,selected:false},
            {available:false,user:false,id:2,selected:false},
            {available:true,user:false,id:3,selected:false},
            {available:false,user:false,id:4,selected:false},
            {available:true,user:false,id:5,selected:false},
            {available:true,user:false,id:6,selected:false},
            {available:false,user:false,id:7,selected:false},
            {available:false,user:false,id:8,selected:false},
            {available:true,user:false,id:9,selected:false},
            {available:false,user:false,id:10,selected:false},
            {available:true,user:false,id:11,selected:false},
            {available:true,user:false,id:12,selected:false},
            {available:false,user:false,id:13,selected:false},
            {available:true,user:false,id:14,selected:false},
            {available:false,user:false,id:15,selected:false},
            {available:true,user:false,id:16,selected:false},
            {available:true,user:false,id:17,selected:false},
            {available:false,user:false,id:18,selected:false},
            {available:true,user:false,id:19,selected:false},
            {available:true,user:false,id:20,selected:false}]

      },

   ]
})